"""added a new column

Revision ID: bfaf5d761097
Revises: bb7ea8ef011a
Create Date: 2021-08-14 17:10:46.723610

"""

# revision identifiers, used by Alembic.
revision = 'bfaf5d761097'
down_revision = 'bb7ea8ef011a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
